import { useEffect, useRef, useState } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { ChevronDown, HelpCircle, MessageCircle } from 'lucide-react';

gsap.registerPlugin(ScrollTrigger);

const faqs = [
  {
    question: 'What is CodeFlow and how does it work?',
    answer: 'CodeFlow is an AI-powered IDE that combines two AI systems: ExplainAI, which teaches and explains code concepts, and CodeAI, which writes production-ready code. As you code, ExplainAI provides real-time explanations while CodeAI helps you write better code faster.',
  },
  {
    question: 'Is CodeFlow free to use?',
    answer: 'Yes! CodeFlow offers a generous free tier with 100 AI requests per month, basic code generation, and error explanations. For unlimited access and advanced features, you can upgrade to our Pro plan starting at $19/month.',
  },
  {
    question: 'Which IDEs and editors are supported?',
    answer: 'CodeFlow supports VS Code, all JetBrains IDEs (IntelliJ, WebStorm, PyCharm, GoLand), Vim/Neovim, with Sublime Text, Atom, and Emacs support coming soon. We also offer a web-based IDE and CLI for maximum flexibility.',
  },
  {
    question: 'How is my code kept secure?',
    answer: 'Security is our top priority. Your code is encrypted in transit and at rest. We never store your code permanently - it\'s only processed to generate responses. Enterprise customers can opt for on-premise deployment for complete control.',
  },
  {
    question: 'Can I use CodeFlow for commercial projects?',
    answer: 'Absolutely! Both free and paid plans allow commercial use. The code generated by CodeAI is yours to use however you want. Pro and Enterprise plans include additional features like team collaboration and custom AI training.',
  },
  {
    question: 'What programming languages are supported?',
    answer: 'CodeFlow supports 50+ programming languages including JavaScript, TypeScript, Python, Java, Go, Rust, C++, Ruby, PHP, and more. Our AI is continuously trained on the latest language features and best practices.',
  },
  {
    question: 'How does the MCP server integration work?',
    answer: 'MCP (Model Context Protocol) servers allow CodeFlow to connect with your existing tools like GitHub, Vercel, MongoDB, and more. This enables context-aware code generation that understands your project\'s infrastructure.',
  },
  {
    question: 'Is there a team or enterprise plan?',
    answer: 'Yes! Our Enterprise plan includes SSO, audit logs, dedicated support, SLA guarantees, and the option for on-premise deployment. Contact our sales team for custom pricing based on your team size and needs.',
  },
];

export const FAQ = () => {
  const sectionRef = useRef<HTMLElement>(null);
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  useEffect(() => {
    const section = sectionRef.current;
    if (!section) return;

    const ctx = gsap.context(() => {
      // Title animation
      gsap.fromTo(
        '.faq-title',
        { y: 50, opacity: 0 },
        {
          y: 0,
          opacity: 1,
          duration: 0.8,
          ease: 'expo.out',
          scrollTrigger: {
            trigger: section,
            start: 'top 70%',
            toggleActions: 'play none none none',
          },
        }
      );

      // FAQ items
      gsap.fromTo(
        '.faq-item',
        { y: 30, opacity: 0 },
        {
          y: 0,
          opacity: 1,
          duration: 0.5,
          stagger: 0.1,
          delay: 0.2,
          ease: 'expo.out',
          scrollTrigger: {
            trigger: section,
            start: 'top 60%',
            toggleActions: 'play none none none',
          },
        }
      );
    }, section);

    return () => ctx.revert();
  }, []);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section
      id="faq"
      ref={sectionRef}
      className="relative py-16 sm:py-20 md:py-24 lg:py-32 bg-[#0a0a0a] overflow-hidden"
    >
      {/* Background */}
      <div className="absolute inset-0">
        <div 
          className="absolute inset-0 opacity-5"
          style={{
            backgroundImage: `
              linear-gradient(rgba(0, 255, 136, 0.1) 1px, transparent 1px),
              linear-gradient(90deg, rgba(0, 255, 136, 0.1) 1px, transparent 1px)
            `,
            backgroundSize: '50px 50px',
          }}
        />
      </div>

      <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-12 md:mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-cyan/10 border border-cyan/30 mb-6">
            <HelpCircle className="w-4 h-4 text-cyan" />
            <span className="text-sm font-medium text-cyan">FAQ</span>
          </div>
          <h2 className="faq-title font-display font-bold text-3xl sm:text-4xl md:text-5xl text-white mb-4">
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-base sm:text-lg text-gray-400">
            Everything you need to know about CodeFlow
          </p>
        </div>

        {/* FAQ Items */}
        <div className="space-y-3 sm:space-y-4">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className="faq-item rounded-2xl bg-dark-card border border-gray-800 overflow-hidden transition-all duration-300 hover:border-gray-700"
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="w-full flex items-center justify-between p-4 sm:p-5 md:p-6 text-left"
              >
                <span className="font-display font-medium text-white pr-3 sm:pr-4">
                  {faq.question}
                </span>
                <ChevronDown 
                  className={`w-5 h-5 text-neon-green flex-shrink-0 transition-transform duration-300 ${
                    openIndex === index ? 'rotate-180' : ''
                  }`}
                />
              </button>
              
              <div 
                className={`overflow-hidden transition-all duration-300 ${
                  openIndex === index ? 'max-h-96' : 'max-h-0'
                }`}
              >
                <div className="px-6 pb-6 text-gray-400 leading-relaxed">
                  {faq.answer}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Contact CTA */}
        <div className="mt-12 text-center">
          <div className="inline-flex items-center gap-3 p-6 rounded-2xl bg-dark-card border border-gray-800">
            <MessageCircle className="w-6 h-6 text-neon-green" />
            <div className="text-left">
              <p className="text-white font-medium">Still have questions?</p>
              <p className="text-gray-500 text-sm">
                We&apos;re here to help!{' '}
                <a href="#" className="text-neon-green hover:underline">
                  Contact our support team
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};
